build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related production1 APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}b564b7b3245b5fb6e3772d61104320d48808ff41cdfad600d532904ba03e262b90d07e2b35aac4ae9ade292214e0a009"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
